require 'httparty'
require 'pry'
require 'open-uri'

require_relative './tvshow/version'
require_relative './tvshow/cli'
require_relative './tvshow/show'
require_relative './tvshow/scraper'
require_relative './tvshow/genre'
require_relative './tvshow/type'