require 'httparty'
require 'pry'
require 'open-uri'
require 'colorize'

require_relative './tvshow/version'
require_relative './tvshow/cli'
require_relative './tvshow/show'
require_relative './tvshow/tvapi'
require_relative './tvshow/genre'
require_relative './tvshow/type'
require_relative './tvshow/cast'
require_relative './tvshow/search'